from gtts import gTTS
import os

myText = "this is audio generated by my text to speech generator, fuck you Msi";

language = 'en'

output = gTTS(text=myText, lang=language)

output.save("msiFucker.mp3")

os.system("start msiFucker.mp3")
