version: 2
jobs:
  build:
    machine: true
    working_directory: ~/typescript-graphql-test
    steps:
      - checkout
      - run:
          name: move into the nest-back directory
          command: |
            cd nest-back
      - run:
          name: Install Node Version Manager
          command: |
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install v8.12.0
            nvm alias default v8.12.0
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"" >> $BASH_ENV
      - run:
          name: Start Prisma server
          command: |
            npm install && npm install -g prisma
            docker-compose up -d
            cd prisma
            sleep 20
            prisma deploy
      - run: npm run test