# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Nest.js CI
on:
  push:
    branches: 
     - master
     - development
  pull_request:
    branches:  
     - master
     - development
env:
  CI: 1
  GOOGLE_CLIENT_ID: '201037185690-g3gkgbfa2m13iepgee7qljkkh5iol1b9.apps.googleusercontent.com'
  GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
  JWT_SECRET: 'THESECRET'
  EXPIRY_TIME: '10800s'
  DATABASE_URL: 'mysql://user:password@localhost:3306/test'
  TESTEMAIL: 'test.email@test.com'
  TESTPASSWORD: 'TestPassword123*'

jobs:
  build:
    name: CI,Build,Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
          DATABASE_URL: 'mysql://user:password@localhost:3306/test'
          TESTEMAIL: 'test.email@test.com'
          TESTPASSWORD: 'TestPassword123*'
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3


    steps:
      - uses: actions/checkout@v1

      - name: Verify MariaDB connection
        working-directory: ./nest-back
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done

      - uses: actions/checkout@v2
        name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}


      - name: npm CI(clean install)
        working-directory: ./nest-back
        run: npm ci
      - name: npm build
        working-directory: ./nest-back
        run: npm run build --if-present
      - name: npm Workout Tests
        working-directory: ./nest-back
        run: npm run test:workoutTest
      - name: npm User Tests
        working-directory: ./nest-back
        run: npm run test:userTest
      - name: npm Client tests
        working-directory: ./nest-back
        run: npm run test:clientTest

