# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Nest.js CI
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
jobs:
  build:
    name: CI,Build,Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
        name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm CI(clean install)
        working-directory: ./nest-back
        run: npm ci
      - name: npm build
        working-directory: ./nest-back
        run: npm run build --if-present
      - name: npm Workout Unit Tests
        working-directory: ./nest-back
        run: npx jest --coverage --detectOpenHandles --forceExit --testPathPattern=test/Workout/UnitTest
