# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Nest.js CI
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
env:
  CI: 1
  PRISMA_TELEMETRY_INFORMATION: 'prisma-examples test-sql-server.yaml'
  DATABASE_URL: 'mysql://root:@localhost:3306/test'
  GOOGLE_CLIENT_ID: '201037185690-g3gkgbfa2m13iepgee7qljkkh5iol1b9.apps.googleusercontent.com'
  GOOGLE_SECRET: '2xP2IbH3SQVFg0qgFOG7Q198'
  JWT_SECRET: 'THESECRET'
  EXPIRY_TIME: '10800s'
  
jobs:
  build:
    name: CI,Build,Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        os: [ubuntu-latest]
        
    steps:
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it
      
      - uses: mirromutth/mysql-action@v1.1
        name: Set up MySQL
        with:
          mysql database: 'test' # Optional, default value is "test". The specified database which will be create
          
      - uses: actions/checkout@v2
        name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm CI(clean install)
        working-directory: ./nest-back
        run: npm ci
      
      - name: npm build
        working-directory: ./nest-back
        run: npm run build --if-present
      - name: npm Workout
        working-directory: ./nest-back
        run: npm test

